### ISSUE TITLE
Multiple paragraphs

### ISSUE THREAD

**Issue by jspitz** [pietvo/multirow#1]
I don't know if it is possible at all, and if so, how difficult it is, but it would be good if `\multirow` would accept multiple paragraphs.

E.g., see https://tex.stackexchange.com/questions/134980/multiple-paragraphs-in-a-multirow-cell

**Comment by pietvo** [comment]
Thanks for bringing this to my attention. I wasn't aware of this.
It is very easy to solve. I will release an update this week/weekend.

**Comment by jspitz** [comment]
Excellent, thanks for the swift response!

**Comment by jspitz** [comment]
Works as of v. 2.7
