### ISSUE TITLE
Incorrect description of negative `nrows`

### ISSUE THREAD

**Issue by sim642** [pietvo/multirow#3]
The documentation has the following:
https://github.com/pietvo/multirow/blob/0edc749bc112b074e2effc6b2175a182426a5e6c/multirow.dtx#L230-L233

For positive `nrows`, it says that, e.g. 3 means the current row and 2 rows below it (total 3).
For negative `nrows`, it says that, e.g. -3 means the current row and 4 rows above it (total 5).

I think this is wrong, as far as I understand, -3 means the current row and 2 rows above it (total 3). I think the formula should be `-nrows-1` instead (not `1-nrows`).

**Comment by pietvo** [comment]
You are right. I'll change the documentation.
